# Generated by Django 3.1.7 on 2021-03-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brief_description',
            field=models.CharField(default='Learn about <django.db.models.fields.CharField> in this post!', max_length=1000, verbose_name='краткое описание'),
        ),
    ]
