# Generated by Django 3.1.7 on 2021-04-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_brief_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('posts', models.ManyToManyField(to='blog.Post', verbose_name='Блоги')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
    ]
